# Generated by Django 2.1 on 2018-08-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KirURLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=100)),
                ('Shortcode', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=100)),
                ('TimeCreate', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
