# Generated by Django 2.0.7 on 2018-07-22 11:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=3)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
            managers=[
                ('companies', django.db.models.manager.Manager()),
            ],
        ),
    ]
