# Generated by Django 2.0.7 on 2018-07-25 16:23

from django.db import migrations
from django.utils.text import slugify

def slugify_title(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Post = apps.get_model('model_migrate', 'Post')
    for post in Post.objects.all():
        post.slug = slugify(post.title)
        post.save()
class Migration(migrations.Migration):

    dependencies = [
        ('model_migrate', '0002_post_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_title)
    ]
